---
abstract: 'Primitive Geometry Entities'
author:
  - 'Cory Watson <gphat@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Geometry-Primitive
no_index:
  directory:
    - inc
    - t
requires:
  Check::ISA: 0.04
  Math::Complex: 1.54
  Moose: 0.57
  MooseX::AttributeHelpers: 0.13
  MooseX::Clone: 0.03
  MooseX::Storage: 0.14
version: 0.11
