---
abstract: 'Primitive Geometry Entities'
author:
  - 'Cory Watson, C<< <gphat@cpan.org> >>'
  - 'Cory Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  JSON::Any: 1.22
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geometry-Primitive
no_index:
  directory:
    - inc
    - t
requires:
  Check::ISA: 0.04
  Math::Complex: 1.56
  Moose: 0.92
  MooseX::Clone: 0.04
  MooseX::Storage: 0.23
resources:
  license: http://dev.perl.org/licenses/
version: 0.23
