---
abstract: 'Primitive Geometry Entities'
author:
  - 'Cory Watson <gphat@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geometry-Primitive
no_index:
  directory:
    - inc
    - t
requires:
  Check::ISA: 0.04
  Math::Complex: 1.54
  Moose: 0.57
  MooseX::AttributeHelpers: 0.13
  MooseX::Clone: 0.03
  MooseX::Storage: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
